# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Regression Build

on:
  push:
    branches: [master, release]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - run: npm install
      - run: npm run ci:build
        env:
          CI: true

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: npm run ci:e2e

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/release'
    steps:
      - run: npm run ci:deploy
