# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Regression Build

on:
  push:
    branches:
      - master
      - release
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Install
        run: npm ci
        env:
          CI: true
      - name: Build
        run: npm run ci:build
        env:
          CI: true
      - name: Test
        run: npm run ci:e2e
        env:
          CI: true
      - name: Deploy
        run: |
          sudo npm install -g firebase-tools
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --project gblaster-player
        env:
          CI: true
        if: github.ref == 'refs/heads/release' && github.event_name == 'push'
